# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Pacman new Theme modify by oser"
license = "MIT"
description = ""
homepage = "https://oser.space/"
tags = ["", ""]
features = ["", ""]
min_version = 0.16

[author]
  name = "oser"
  homepage = "https://oser.space/"

# If porting an existing theme
[original]
  name = "coderzh"
  homepage = "http://blog.coderzh.com"

