BaseURL = "https://oser.space/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "专心打杂"
Theme = "hugo-oser"
pygmentsStyle = "default"
pygmentsUseClasses = true


[Author]
  Name = "oser"

[Params]
  AuthorHomepage = "https://oser.space/"
  BottomIntroduce = "Oser's Blog"
  Description = ""
  Subtitle = "客户端 前后端 操作系统 golang c/c++ 各种脚本，努力做全栈"
  zhihu = "ou-xie-te-36"
  Weibo = "wormz"
  WeiboID = 1689508020
  #Twitter = "xxxx"
  GitHub = "oserz"
  #Facebook = "xxxx"
  #LinkIn = "xxxx"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  # DuoShuoShortName = ""
  #DisqusShortName = ""
  #wangyiyunID = "1111"
  BDAnalyticsID = "1111"
  GitHubCID = "1111"
  GitHubCS = "1111"
  GitHubRepo = "https-oser.space"
  
  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
